workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'artifacts'
          include: true
    scripts:
      - name: Download artifacts from build 5f6dfeb029657a3ca6977423
        script: |
          brew install jq
          curl \
            -H "Content-Type: application/json" \
            -H "x-auth-token: 4nh2gDBK62WJ5QPl0SStBw" \
            --request GET https://api.codemagic.io/builds/5f6dfeb029657a3ca6977423 | \
            jq -r '.build."artefacts" | .[] | .url' | \
            xargs wget -i {}
    publishing:
      app_store_connect:
        apple_id: myemail@gmail.com
        password: abcde
    artifacts:
      - '*.ipa'
