workflows:
  yaml-workflow:
    name: Yaml Workflow
    environment:
      vars:
        MY_VARIABLE: YAML
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - echo "MY_VARIABLE=$MY_VARIABLE"
    artifacts:
      - flutter_drive.log
