workflows: 
  default-workflow: 
    name: "Default Workflow"
    triggering:       
      events: 
        - push
      branch_patterns: 
        - include: true
          pattern: webhook
    scripts:
      - |
        curl https://postman-echo.com/post \
          --header "Content-Type: application/json" \
          --request POST \
          --data @- <<REQUEST_BODY
            {
              "project": {
                "id": "project_id",
                "name": "Lingvist Android",
                "platform": "android",
                "repository": "repo",
                "web_url": "https://api.codemagic.io/apps/$FCI_PROJECT_ID"
              },
              "build_config": {
                "id": "build_config_id",
                "branch": "$FCI_BRANCH",
              },
              "build": {
                "id": "build_id",
                "build_number": "$BUILD_NUMBER",
                "commit_hash": "$FCI_COMMIT",
                "web_url": "https://codemagic.io/app/$FCI_PROJECT_ID/build/$FCI_BUILD_ID"
              }
            }
            REQUEST_BODY
