workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'artifacts'
          include: true
    scripts:
      - name: Download artifacts from build 5f6dfeb029657a3ca6977423
        script: |
          curl -s --request GET \
            -H "Content-Type: application/json" \
            -H "x-auth-token: 4nh2gDBK62WJ5QPl0SStBw" \
            https://api.codemagic.io/builds/5f6dfeb029657a3ca6977423 | \
            python3 -c "import sys, json; print('\n'.join([artifact['url'] for artifact in json.load(sys.stdin)['build']['artefacts']]))" | \
            xargs wget -i {}
    publishing:
      app_store_connect:
        apple_id: myemail@gmail.com
        password: abcde
    artifacts:
      - '*.ipa'
