workflows:
  default-workflow:
    name: Default Workflow
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: 'master'
          include: true
          source: true
    scripts:
      - |
        # set up debug keystore
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
          -alias androiddebugkey \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter build appbundle --debug
      - |
        # generate universal apk signed with debug key
        universal-apk generate \
          --ks ~/.android/debug.keystore \
          --ks-pass android \
          --ks-key-alias androiddebugkey \
          --key-pass android \
          --pattern 'build/**/outputs/**/*.aab'
    publishing:
      scripts:
        - name: Start a new build with generated artifacts
          script: |
            APP_LINK=$(echo $FCI_ARTIFACT_LINKS | jq '.[] | select(.name | endswith(".apk")) | .url')

            curl -H "Content-Type: application/json" -H "x-auth-token: 4nh2gDBK62WJ5QPl0SStBw" \
              --data '{
                  "appId": "5f2aaf2fc4bf2d001800d81b", 
                  "workflowId": "default-workflow",
                  "branch": "master", 
                  "environment": { 
                      "variables": { 
                          "APP_TO_TEST_URL": $APP_LINK
                      }
                  }
              }' \
              https://api.codemagic.io/builds
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
