--- 
workflows: 
  default-workflow: 
    name: "Default Workflow"
    triggering:       
      events: 
        - push
      branch_patterns: 
        - include: true
          pattern: webhook
    scripts: 
      - "echo $FCI_COMMIT"
      - "echo $FCI_PROJECT_ID"
      - "echo $FCI_BUILD_ID"
      - |
        curl https://postman-echo.com/post \
          --header "Content-Type: application/json" \
          --request POST \
          --data @- <<REQUEST_BODY
            {
              "project": {
                "id": "project_id",
                "name": "Codemagic",
                "platform": "Android",
                "web_url": "https://api.codemagic.io/apps/$FCI_PROJECT_ID"
              },
            }
            REQUEST_BODY
