workflows: 
  default-workflow: 
    name: "Default Workflow"
    triggering:       
      events: 
        - push
      branch_patterns: 
        - include: true
          pattern: webhook
    scripts:
      - |
        # set up debug keystore
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
          -alias androiddebugkey \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter build appbundle --debug
      - |
        # generate universal apk signed with debug key
        universal-apk generate \
          --ks ~/.android/debug.keystore \
          --ks-pass android \
          --ks-key-alias androiddebugkey \
          --key-pass android \
          --pattern 'build/**/outputs/**/*.aab'
    publishing:
      scripts: 
        - name: Webhook notification
          script: |
            export PROJECT_URL=https://codemagic.io/app/${FCI_PROJECT_ID}
            # export VERSION_CODE=$(grep -o "versionCode\s\+\d\+" app/build.gradle | awk '{ print $2 }')
            # export VERSION_NAME=$(awk '/versionName\s".*"/{ print $2 }' app/build.gradle | tr -d \''"\')

            curl https://postman-echo.com/post \
              --header "Content-Type: application/json" \
              --request POST \
              --data @- <<BODY
                {
                  "project": {
                    "name": "Lingvist Android",
                    "id": "$FCI_PROJECT_ID",
                    "url": "$PROJECT_URL",
                  },
                  "build": {
                    "id": "$FCI_BUILD_ID",
                    "branch": "$FCI_BRANCH",
                    "number": "$BUILD_NUMBER",
                    "version_code": "$VERSION_CODE",
                    "version_name": "$VERSION_NAME",
                    "url": "${PROJECT_URL}/build/${FCI_BUILD_ID}"
                  },
                  "commit": {
                    "hash": "$FCI_COMMIT",
                    "commit_subject": "$(git show -s --format=%s)",
                    "commit_body": "$(git show -s --format=%b)"
                  }
                  "artefacts": "$FCI_ARTIFACT_LINKS"
                }
                BODY
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk